Factory.define :profile do |p|
  p.user {|u| u.association(:user)}
  p.first_name "amit"
  p.middle_name "kumar"
  p.last_name "gupta"
  p.title "Mr."
  p.blood_group "A"
  p.group "2011"
  p.gender "Male"
  p.house_name "Eklavya"
  p.date_of_birth "1990-06-22"
  p.relationship_status "single"
  p.anniversary_date ""
  p.spouse_name ""
  p.maiden_name ""
  p.professional_qualification "B.E."
  p.about_me "cool guy"
  p.activities "sports"
  p.is_active true
  p.location "jaipur"
  p.address_line1 "A-111"
  p.address_line2 "adarsh nagar"
  p.city "jaipur"
  p.postal_code "302010"
  p.country "india"
  p.state "rajasthan"
  p.landline "0141-2212121"
  p.mobile "9800000000"
  p.status_message "at office"
  p.website "www.google.com"
  p.blog "my first blog"
  p.flicker_username "x"
  p.linkedin_name "x"
  p.twitter_username "x"
  p.aim_name "x"
  p.msn_username "x"
  p.yahoo_name "x"
  p.gtalk_name "x"
  p.skype_name "x"
  p.delicious_name "x"
  p.icon_file_name "x"
  p.default_permission "Everyone"
end

Factory.define :profile2, :class => Profile do |p|
  p.user {|u| u.association(:user)}
  p.first_name "sachin"
  p.middle_name ""
  p.last_name "singh"
  p.title "Mr."
  p.blood_group "B"
  p.group "2011"
  p.gender "Male"
  p.house_name "Shravan"
  p.date_of_birth "1991-06-22"
  p.relationship_status "Married"
  p.anniversary_date "2010-06-22"
  p.spouse_name "abc"
  p.maiden_name ""
  p.professional_qualification "doctor"
  p.about_me "developer"
  p.activities "playing cricket"
  p.is_active true
  p.location "mumbai"
  p.address_line1 "B-123"
  p.address_line2 "andheri"
  p.city "mumbai"
  p.postal_code "302121"
  p.country "india"
  p.state "maharashtra"  
  p.landline "022-25454456"
  p.mobile "9850000000"
  p.status_message "at home"
  p.website "x"
  p.blog "my second blog"
  p.flicker_username "x"
  p.linkedin_name "x"
  p.twitter_username "x"
  p.aim_name "x"
  p.msn_username "x"
  p.yahoo_name "x"
  p.gtalk_name "x"
  p.skype_name "x"
  p.delicious_name "x"
  p.icon_file_name "x"
  p.default_permission "Friends"
end