Factory.define :profile do |p|
  p.user {|u| u.association(:user)}
  p.first_name "amit"
  p.last_name "gupta"
  p.title "x"
  p.blood_group "x"
  p.group "2011"
  p.gender "Male"
  p.house_name "x"
  p.date_of_birth "x"
  p.relationship_status "x"
  p.anniversary_date "x"
  p.spouse_name "x"
  p.professional_qualification "x"
  p.about_me "x"
  p.activities "x"
  p.is_active true
  p.location "x"

  p.address_line1 "x"
  p.address_line2 "x"
  p.city "x"
  p.postal_code "x"
  p.country "x"
  p.state "x"
  p.landline "x"
  p.mobile "x"
  p.status_message "click here to set status"
  p.website "x"
  p.blog "x"
  p.flicker_username "x"
  p.linkedin_name "x"
  p.twitter_username "x"
  p.aim_name "x"
  p.msn_username "x"
  p.yahoo_name "x"
  p.gtalk_name "x"
  p.skype_name "x"
  p.delicious_name "x"
  p.icon_file_name "x"
end

Factory.define :profile2, :class => Profile do |p|
  p.user {|u| u.association(:user)}
  p.first_name "sachin"
  p.last_name "singh"
  p.title "x"
  p.blood_group "x"
  p.group "2011"
  p.gender "Male"
  p.house_name "x"
  p.date_of_birth "x"
  p.relationship_status "x"
  p.anniversary_date "x"
  p.spouse_name "x"
  p.professional_qualification "x"
  p.about_me "x"
  p.activities "x"
  p.location "x"
  p.address_line1 "x"
  p.address_line2 "x"
  p.city "x"
  p.postal_code "x"
  p.country "x"
  p.state "x"
  p.is_active true
  p.landline "x"
  p.mobile "x"
  p.status_message "click here to set status"
  p.website "x"
  p.blog "x"
  p.flicker_username "x"
  p.linkedin_name "x"
  p.twitter_username "x"
  p.aim_name "x"
  p.msn_username "x"
  p.yahoo_name "x"
  p.gtalk_name "x"
  p.skype_name "x"
  p.delicious_name "x"
  p.icon_file_name "x"
end
